import {Box,Button,Chip,CircularProgress,Dialog,DialogActions,DialogContent,DialogContentText,DialogTitle,Paper,Skeleton,Stack,Typography} from '@mui/material';
import type {ButtonProps} from '@mui/material';

export const PR_STATUS=['','Draft','Submitted','Approved','Rejected','PO Created','Delivered','Completed'];
export const PO_STATUS=['','Created','Delivered','Completed'];
export const CURRENCIES=['','INR','USD','EUR','GBP'];
const statusColors:Record<string,'default'|'primary'|'success'|'error'|'warning'|'info'>={Draft:'default',Submitted:'info',Approved:'success',Rejected:'error','PO Created':'primary',Delivered:'warning',Completed:'success',Created:'primary'};
export function StatusChip({status,type='pr'}:{status:number;type?:'pr'|'po'}){const label=(type==='pr'?PR_STATUS:PO_STATUS)[Number(status)]??'Unknown';return <Chip size="small" label={label} color={statusColors[label]??'default'} variant={label==='Draft'?'outlined':'filled'} sx={{fontWeight:600}}/>}
export function PageHeader({title,subtitle,action}:{title:string;subtitle?:string;action?:React.ReactNode}){return <Stack direction={{xs:'column',sm:'row'}} justifyContent="space-between" alignItems={{xs:'flex-start',sm:'center'}} gap={1} mb={1.25}><Box><Typography variant="h5">{title}</Typography>{subtitle&&<Typography variant="caption" color="text.secondary" display="block" mt={.15}>{subtitle}</Typography>}</Box>{action}</Stack>}
export function FullPageLoader({skeleton=false}:{skeleton?:boolean}){return <Box sx={{py:8,display:'flex',justifyContent:'center'}}>{skeleton?<Stack width="100%" spacing={2}><Skeleton height={52}/><Skeleton variant="rounded" height={280}/></Stack>:<CircularProgress/>}</Box>}
export function LoadingActionButton({loading,children,disabled,...props}:ButtonProps&{loading?:boolean}){return <Button {...props} disabled={disabled||loading}>{loading&&<CircularProgress size={18} color="inherit" sx={{mr:1}}/>}{children}</Button>}
export function ConfirmDialog({open,title,message,confirmLabel='Confirm',loading=false,danger=false,onClose,onConfirm}:{open:boolean;title:string;message:string;confirmLabel?:string;loading?:boolean;danger?:boolean;onClose:()=>void;onConfirm:()=>void}){return <Dialog open={open} onClose={loading?undefined:onClose} fullWidth maxWidth="xs"><DialogTitle>{title}</DialogTitle><DialogContent><DialogContentText>{message}</DialogContentText></DialogContent><DialogActions><Button onClick={onClose} disabled={loading}>Cancel</Button><LoadingActionButton variant="contained" color={danger?'error':'primary'} loading={loading} onClick={onConfirm}>{confirmLabel}</LoadingActionButton></DialogActions></Dialog>}
export const gridPaperSx={p:1,flex:'1 1 0',minHeight:0,border:'1px solid',borderColor:'divider',boxShadow:'0 4px 16px rgba(15,23,42,.05)',borderRadius:2,overflow:'hidden','& .MuiDataGrid-root':{border:0,fontSize:12.5,height:'100%'},'& .MuiDataGrid-autoHeight':{height:'100%!important'},'& .MuiDataGrid-columnHeaders':{bgcolor:'action.hover',fontWeight:700},'& .MuiDataGrid-columnHeaderTitle':{fontWeight:700},'& .MuiDataGrid-row:hover':{bgcolor:'action.hover'},'& .MuiDataGrid-cell':{py:0},'& .MuiDataGrid-footerContainer':{minHeight:42,mt:'auto'}} as const;
export function GridShell({children}:{children:React.ReactNode}){return <Paper elevation={0} sx={gridPaperSx}>{children}</Paper>}
